# urdf path for rbdl
urdf_path: package://social_robot_description_snu/urdf/social_robot_left_8dof_rbdl.urdf  # for RBDL
# Start & end chain for inverse kinematics
chain_start: Waist_Pitch #robocare_link0 # base link
# robocare_link0 : 8dof / Waist_Roll : 7dof / Waist_Pitch : 6dof
chain_end: left_end_effect_point # end-effector link

# Joint limit
joint_limit_lower: [170.0, -100.0, -170.0, -90.0, -164.0, -55.0] # Waist_Roll, Waist_Pitch, ~ 
joint_limit_upper: [170.0,  94.0, 170.0, 47.0, 170.0, 52.0]

# Link name & dimension for Collision Check
link_data:
  link_name: [Waist_Pitch, Waist_Pitch, LShoulder_Pitch, LShoulder_Roll, LElbow_Yaw, LWrist_Roll, LWrist_Roll, LWrist_Roll] # Link name in URDF file - First 2 links : Body links / Last 2 links : Gripper links
  link_dimension: [[0.125, 0.125, 0.125], [0.125, 0.12, 0.225], [0.04, 0.04, 0.04], [0.03, 0.05, 0.03], [0.04, 0.08, 0.04], [0.035, 0.035, 0.035], [0.025, 0.03, 0.01], [0.025, 0.030, 0.01]] # Width, Depth, Height
  link_position: [[0.0, 0.0, 0.3261], [0.0, 0.0, -0.0], [0.0, -0.0, -0.0], [0.0, -0.0, -0.0], [0.0, 0.0, -0.0], [0.0, -0.0, 0.0], [0.0, 0.08, 0.05], [0.0, 0.08, -0.06]] # x, y, z relative to link's center of mass
  link_orientation: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[40.0, 0.0, 0.0], [-40.0, 0.0, 0.0]] # Roll pitch yaw relative to center of box  
